### ISSUE TITLE
EfficientNet Model

### ISSUE THREAD

**Issue by kiran-collab** [wingman-jr-addon/model#2]
Hi!
Which model version/ release is based on EfficientNet? I wish to implement the efficient model for this plugin
May I please request you to address the above at the earliest!

**Comment by wingman-jr-addon** [comment]
The only released model is SQRXR 62, which is MobileNetV2-based - that's what's in [release 2.0.1](https://github.com/wingman-jr-addon/wingman_jr/tree/release-2.0.1). I've been experimenting heavily with EfficientNet and now EfficientNetLite, but have not settled on a final model. Latest experiment is [SQRXR 109 on master](https://github.com/wingman-jr-addon/wingman_jr/tree/master/sqrxr_109_graphopt) but intentionally not released over in this repo yet.  It's not ready yet, but I think EfficientNet Lite L0 will likely be the base for the next release. See the thread [over here](https://github.com/wingman-jr-addon/wingman_jr/issues/64)

However, if you're feeling ambition and try to use it: do note that I have also fused the classifier and threshold outputs now as well. To get the confidence score like you're used to you will need e.g. `let threshold = sqrxrScore[1][0];` and then a threshold cutoff of e.g. `0.002120536`. Just keep in mind you're going to be on your own because I haven't released it yet.

**Comment by kiran-collab** [comment]
Respected Sir
1. 'SQRXR on master' is based on which model?
2. Can you share any intermediary model which is based on EfficientNet (maybe privately, if possible)?
3. Can you please share the dataset for which you have trained the model?
4. I have a pre trained model and its h5 file. Can you guide me how I can host that model in the plugin. But I guess it won't work as I am using two classes namely 'Non-porn' and 'Porn' while yours has four classes.

I would be grateful if you could kindly address the above queries!

**Comment by wingman-jr-addon** [comment]
1. SQRXR 109 on master is based on EfficientNet Lite L0.  See [this thread](https://github.com/wingman-jr-addon/wingman_jr/pull/91). Keep in mind that is a slight deviation from EfficientNet.
2. The intermediate model setup of SQRXR 109 is similar to SQRXR 62 here except that instead of feeding the 4-class classifier into the second stage model I feed the last convolutional layer's output features (size 1280) into a small net instead. So the whole model is there. I will share .h5's when I do a release... 
3. As per [the README](https://github.com/wingman-jr-addon/model), no.
4. Well keep in mind that the intermediate models output 4 classes, but the second stage model turns that into a threshold. The [description for SQRXR 62](https://github.com/wingman-jr-addon/model/tree/master/sqrxr_62) is still fairly close. My comment above is just that I now output BOTH the classifier as well as the threshold. So in theory you can pick a threshold and view it as a binary classifier - however, keep in mind that I block more than what may be considered Porn.

As for hosting your model in the plugin... Well, you're going to need to dig a bit. If you *really* want to do it, I recommend taking your binary classifier and generating a ROC curve (for example by sklearn's roc_curve), then regenerating the data in roc.js. Note you only really need the TPR, FPR, and threshold at this time. Then, select cutpoints that represent "trusted" "neutral" and "untrusted" levels. Then, convert your .h5 using tensorflowjs_converter and using the graph output and drop it in/update the paths. None of it is hard, but the process as a whole takes a while.

Now, you can try SQRXR 109 but like I said - you're on your own. What I can say is that I expect the next model release will be similar to SQRXR 109 so at least upgrading will probably be not too painful. But the type of help you're asking for goes well beyond the scope of this repo. Do you have your own repo with your own project?

**Comment by wingman-jr-addon** [comment]
(Take a peek at SQRXR 112 now)

**Comment by kiran-collab** [comment]
Respected Sir
Hi!
I am extremly sorry for the late reply.
I haven't created any repo on github but I have the classifier and training repo in my local storage. 
As per your instructions, I am trying to convert my classifier to roc through sklearn and then to json files. 
I have one query:
Does the two class classifier affect in a negative way to the plugin. Or is it just creating the roc curve from sklearn, then regenerating in roc.js and converting the h5 file to json and bin files ?
I would be grateful I would be grateful if you could kindly address the same.

**Comment by wingman-jr-addon** [comment]
I am not sure what you mean by this statement: `Does the two class classifier affect in a negative way to the plugin.` Can you explain more?

**Comment by wingman-jr-addon** [comment]
Also, please consider creating a repository. If you have questions about your code and your model it will be better to discuss them as issues on your repository rather than here.
