### ISSUE TITLE
Other areas of application (blocking other types of content)

### ISSUE THREAD

**Issue by Ro-Den** [wingman-jr-addon/model#8]
Thanks for the great add-on and the information you provide!

Are you interested in other areas of application? Blocking other types of content? E.g., commercial propaganda, aka advertisement );

If not. Is it possible for the add-on to utilize custom models? I've just started studying PyTorch, so it's not too late to switch to TensorFlow, Keras.

**Comment by wingman-jr-addon** [comment]
Thanks @Ro-Den ! Well, in this case, I've been mostly focused on NSFW images rather than other types of content. I think to filter other types of content you'd probably have to make some significant changes not only to the model but also to the addon itself in doing predictions - my guess is you might have better luck looking at using uBlock Origin or something as a base if your goal also includes heavy text filtering etc.

That being said, let's say you wanted to fork and modify the addon to do more - how would you do it?

1. First, this repository is just the model. The main addon is over here: https://github.com/wingman-jr-addon/wingman_jr
2. Second, let's say you wanted to just filter images but with a new model. A student was interested in doing this and I wrote them some further details over here: https://github.com/wingman-jr-addon/model/issues/1 It's a bit dated, but I think you'd find it helpful. One quite important fact to keep in mind is that the addon since 2.x has been structured as essentially a client-server application in order to allow Tensorflow.js to run GPU code well, and that has a big impact on the code structure.
3. Now, while it isn't structured for it well right now, if you wanted to do text and other content filtering, I'd recommend looking into the section of code where the HTML is scanned for Base64 encoded images and replacing with your own logic. In broad strokes, the HTML is sent over to the processor, and reassembled at this spot: https://github.com/wingman-jr-addon/wingman_jr/blob/bbc1cb8e785c56318d24c0a5b076cf23436e6762/processor.js#L385 That's where the regex for finding data URI's kicks in and you could do other interesting things there.

Note that a great deal of the addon exists to solve annoying problems: trying to handle proper text decoding (and still failing sometimes) as well as the whole client-server architecture existing solely to make the GPU happy. You can find a much more stripped down version of filtering here: https://github.com/wingman-jr-addon/webextensions-examples/blob/make-http-response-example-more-robust/http-response/background.js It's my imperfect attempt at trying to buff up the MDN base example.

Best of luck!

**Comment by wingman-jr-addon** [comment]
@Ro-Den  Feel free to ask more questions, but I'm closing this issue out as stale.
